# Generated by Django 6.1 on 2026-08-20 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('devpost', 'Devpost'), ('luma', 'Luma'), ('mlh', 'MLH'), ('devfolio', 'Devfolio')], db_index=True, max_length=20)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('prizes', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_online', models.BooleanField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='EventSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=500)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('prizes', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_online', models.BooleanField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='events.event')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
