# Generated by Django 6.1 on 2026-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('devpost', 'Devpost'), ('luma', 'Luma'), ('mlh', 'MLH'), ('devfolio', 'Devfolio'), ('lablab', 'LabLab'), ('meetup', 'Meetup')], db_index=True, max_length=20),
        ),
    ]
